/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static pkgfinal.NewJFrame1.Search;

/**
 *
 * @author Design
 */
public class LogIn extends javax.swing.JFrame {

    static LogIn Login;

    /**
     * ئ
     * Creates new form LogIn
     */
    private LogIn() {
        initComponents();
        this.setLocationRelativeTo(null);
        Username.setForeground(Color.GRAY);
        Password.setForeground(Color.GRAY);
        ImageIcon img = new ImageIcon(getClass().getResource("2.png"));
        this.setTitle("LOG IN");
        this.setIconImage(img.getImage());
        this.setResizable(false);
        correct.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        Search_Contract = new javax.swing.JLabel();
        correct = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(440, 450));
        setPreferredSize(new java.awt.Dimension(440, 450));

        jPanel1.setBackground(new java.awt.Color(76, 76, 76));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/2.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Username.setBackground(new java.awt.Color(76, 76, 76));
        Username.setFont(new java.awt.Font("Helvetica World", 0, 18)); // NOI18N
        Username.setForeground(new java.awt.Color(204, 204, 204));
        Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username.setText("Enter Username");
        Username.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFocusLost(evt);
            }
        });
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        Password.setBackground(new java.awt.Color(76, 76, 76));
        Password.setFont(new java.awt.Font("Helvetica World", 0, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(204, 204, 204));
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Password.setText("Enter Password");
        Password.setToolTipText("");
        Password.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        Search_Contract.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/LOGINMOVED.png"))); // NOI18N
        Search_Contract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Search_ContractMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Search_ContractMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Search_ContractMousePressed(evt);
            }
        });

        correct.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        correct.setForeground(new java.awt.Color(255, 0, 51));
        correct.setText("Username Or Password Is Not Correct");

        jButton1.setText("تسجيل الدخول");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(correct, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Search_Contract)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Search_Contract, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Search_ContractMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_ContractMouseExited
        ImageIcon icon = new ImageIcon(getClass().getResource("LOGINMOVED.png"));
        icon.getImage().flush();
        Search_Contract.setIcon(icon);        // TODO add your handling code here:
    }//GEN-LAST:event_Search_ContractMouseExited

    private void Search_ContractMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_ContractMouseEntered
        ImageIcon icon = new ImageIcon(getClass().getResource("lOGIN.png"));
        icon.getImage().flush();
        Search_Contract.setIcon(icon);

        // TODO add your handling code here:
    }//GEN-LAST:event_Search_ContractMouseEntered

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost

        if (Password.getText().equals("")) {
            Password.setForeground(Color.GRAY);
            Password.setText("Enter Password");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusLost

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        if (Password.getText().equals("Enter Password")) {
            Password.setForeground(Color.WHITE);
            Password.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFocusGained

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusLost

        if (Username.getText().equals("")) {
            Username.setForeground(Color.GRAY);
            Username.setText("Enter Username");
        }
    }//GEN-LAST:event_UsernameFocusLost

    private void UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFocusGained
        if (Username.getText().equals("Enter Username")) {
            Username.setForeground(Color.WHITE);
            Username.setText("");
        }
    }//GEN-LAST:event_UsernameFocusGained

    private void Search_ContractMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Search_ContractMousePressed
        if (Username.getText().equals("123") && Password.getText().equals("123")) {
            System.out.print("Done !!!");
            NewJFrame.getMainScreen();
            Login.setVisible(false);

        } else {
            correct.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_ContractMousePressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Login = new LogIn();
                Login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Password;
    private javax.swing.JLabel Search_Contract;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel correct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
  public static LogIn getMainScreen() {
        if (Login == null) {
            return Login = new LogIn();

        } else {

            Login.setVisible(true);

        }
        return Login;
    }
}
