/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ameer;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.ucanaccess.jdbc.*;

/**
 *
 * @author Alaa
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public static MainFrame frame;

    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        getContentPane().setBackground(new java.awt.Color(0, 0, 0));
        setIcons();
    }

    private void setIcons() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appLogo.png")));
        imageHeader.setIcon(new ImageIcon(getClass().getResource("logo.png")));
        ameerAd.setIcon(new ImageIcon(getClass().getResource("ameerAd.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imageHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tv_username = new javax.swing.JLabel();
        et_username = new javax.swing.JTextField();
        tv_number = new javax.swing.JLabel();
        et_number = new javax.swing.JTextField();
        tv_type = new javax.swing.JLabel();
        et_type = new javax.swing.JTextField();
        tv_price = new javax.swing.JLabel();
        et_price = new javax.swing.JTextField();
        et_paid = new javax.swing.JTextField();
        tv_paid = new javax.swing.JLabel();
        tv_phone_number = new javax.swing.JLabel();
        et_notes = new javax.swing.JTextField();
        tv_type_of_paying = new javax.swing.JLabel();
        jComboBox_type_of_paying = new javax.swing.JComboBox();
        tv_notes = new javax.swing.JLabel();
        et_phone_number = new javax.swing.JTextField();
        et_date = new javax.swing.JTextField();
        tv_phone_number1 = new javax.swing.JLabel();
        bt_login = new javax.swing.JButton();
        bt_login1 = new javax.swing.JButton();
        bt_login2 = new javax.swing.JButton();
        bt_login3 = new javax.swing.JButton();
        ameerAd = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("الرئيسية");

        jPanel1.setBackground(new java.awt.Color(248, 249, 249));

        imageHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ameer/logo.png"))); // NOI18N

        tv_username.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_username.setForeground(new java.awt.Color(2, 177, 225));
        tv_username.setText("الاسم");

        et_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_username.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        et_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_number.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_number.setForeground(new java.awt.Color(2, 177, 225));
        tv_number.setText("العدد");

        et_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_type.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_type.setForeground(new java.awt.Color(2, 177, 225));
        tv_type.setText("النوع");

        et_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_type.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        et_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_price.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_price.setForeground(new java.awt.Color(2, 177, 225));
        tv_price.setText("السعر");

        et_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        et_paid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_paid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_paid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_paid.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_paid.setForeground(new java.awt.Color(2, 177, 225));
        tv_paid.setText("الدفعة");

        tv_phone_number.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_phone_number.setForeground(new java.awt.Color(2, 177, 225));
        tv_phone_number.setText("الجوال");

        et_notes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_notes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_notes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_type_of_paying.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_type_of_paying.setForeground(new java.awt.Color(2, 177, 225));
        tv_type_of_paying.setText("الدفع");

        jComboBox_type_of_paying.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox_type_of_paying.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "أسبوعي", "شهري" }));

        tv_notes.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_notes.setForeground(new java.awt.Color(2, 177, 225));
        tv_notes.setText("ملاحظات");

        et_phone_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_phone_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_phone_number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        et_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_phone_number1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_phone_number1.setForeground(new java.awt.Color(2, 177, 225));
        tv_phone_number1.setText("التاريخ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageHeader)
                .addGap(288, 288, 288))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(et_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(et_paid)
                            .addComponent(et_price, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(et_number, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox_type_of_paying, 0, 164, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tv_price, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(tv_number, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)))
                                    .addComponent(tv_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 2, Short.MAX_VALUE)
                                        .addComponent(et_username, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tv_username, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(et_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tv_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(et_type, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tv_type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tv_type_of_paying, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tv_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(et_date, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tv_phone_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(imageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(et_price, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tv_price))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tv_username)
                            .addComponent(et_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tv_number)
                            .addComponent(et_number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et_type, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tv_type))
                        .addGap(2, 2, 2)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tv_paid)
                    .addComponent(tv_phone_number)
                    .addComponent(et_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox_type_of_paying, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tv_type_of_paying))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tv_phone_number1)
                        .addComponent(et_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(tv_notes)
                .addGap(18, 18, 18)
                .addComponent(et_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bt_login.setBackground(new java.awt.Color(2, 175, 255));
        bt_login.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("بحث");
        bt_login.setBorder(null);
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });

        bt_login1.setBackground(new java.awt.Color(2, 175, 255));
        bt_login1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bt_login1.setForeground(new java.awt.Color(255, 255, 255));
        bt_login1.setText("إضافة");
        bt_login1.setBorder(null);
        bt_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_login1ActionPerformed(evt);
            }
        });

        bt_login2.setBackground(new java.awt.Color(2, 175, 255));
        bt_login2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bt_login2.setForeground(new java.awt.Color(255, 255, 255));
        bt_login2.setText("دفع اليوم");
        bt_login2.setBorder(null);
        bt_login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_login2ActionPerformed(evt);
            }
        });

        bt_login3.setBackground(new java.awt.Color(2, 175, 255));
        bt_login3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bt_login3.setForeground(new java.awt.Color(255, 255, 255));
        bt_login3.setText("خروج");
        bt_login3.setBorder(null);
        bt_login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_login3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_login2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(bt_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_login1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_login3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ameerAd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(bt_login1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bt_login2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bt_login3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(ameerAd, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_login3ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_bt_login3ActionPerformed

    private void bt_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_login1ActionPerformed
        String number = et_number.getText();
        String price = et_price.getText();
        String paid = et_paid.getText();
        String name = et_username.getText();
        String date = et_date.getText();
        String type = et_type.getText();
        String phoneNumber = et_phone_number.getText();
        String typeOfPaying = jComboBox_type_of_paying.getSelectedItem().toString();
        String notes = et_notes.getText();
        String arrays[] = {name, number, type, price, paid, phoneNumber, typeOfPaying, date};
        if (checkStrings(arrays)) {
            try {
                Integer.parseInt(number);
                Integer.parseInt(price);
                Integer.parseInt(paid);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "الرجاء إدخال قيم صحيحة");
                return;
            }
            Bought bought = new Bought(name, type, phoneNumber, number, price, paid, notes, typeOfPaying, date);
            addBoughtToTable(bought);
        } else {
            JOptionPane.showMessageDialog(null, "جميع الحقول مطلوبة");
        }
    }//GEN-LAST:event_bt_login1ActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        this.setVisible(false);
        SearchFrame frame = new SearchFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_bt_loginActionPerformed

    private void bt_login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_login2ActionPerformed
        this.setVisible(false);
        TodayPays.getTodayPaysFrame();// TODO add your handling code here:
    }//GEN-LAST:event_bt_login2ActionPerformed

    private boolean checkStrings(String[] arrays) {
        for (int i = 0; i < arrays.length; i++) {
            if (arrays[i].equals("") || arrays[i].equals(null)) {
                return false;
            }
        }
        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame = new MainFrame();
                frame.setVisible(true);
            }
        });
    }

    public static MainFrame getMainFrame() {
        try {
            if (frame == null) {
                frame = new MainFrame();
                frame.setVisible(true);
                return frame;
            } else {
                frame.setVisible(true);
            }
            return frame;
        } catch (Exception e) {
        }
        return null;
    }

    private void addBoughtToTable(Bought bought) {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Alaa\\Documents\\NetBeansProjects\\"
                    + "AmeerAbouShaban\\Ameer.mdb", "", "");

            con.setAutoCommit(false);
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            s.execute("select * from Boughts");
            ResultSet rs = s.getResultSet();
            rs.moveToInsertRow();
            rs.updateString("Name", bought.getName());
            rs.updateString("Type", bought.getType());
            rs.updateString("Phone", bought.getPhoneNumber());
            rs.updateString("Number", bought.getNumber());
            rs.updateString("Price", bought.getPrice());
            rs.updateString("Notes", bought.getNotes());
            rs.updateString("PayingWay", bought.getPayingWay());
            rs.updateString("BoughtDate", bought.getDate());
            int price = Integer.parseInt(bought.getPrice());
            int number = Integer.parseInt(bought.getNumber());
            int totalPrice = price * number;
            int paid = Integer.parseInt(bought.getPaid());
            String restOfMoney = "" + (totalPrice - paid);
            rs.updateString("RestOfMoney", restOfMoney);
            rs.insertRow();           
            con.commit();
            con.close();
            s.close();
            rs.close();
            JOptionPane.showMessageDialog(null, "تمت الإضافة بنجاح");
            JTextField fields[] = {et_notes, et_number, et_paid, et_phone_number, et_price, et_type, et_username, et_date};
            clearAllFields(fields);
        } catch (Exception ex) {
            System.out.println("" + ex.getMessage());
        }
    }

    private void clearAllFields(JTextField fields[]) {
        for (int i = 0; i < fields.length; i++) {
            fields[i].setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ameerAd;
    private javax.swing.JButton bt_login;
    private javax.swing.JButton bt_login1;
    private javax.swing.JButton bt_login2;
    private javax.swing.JButton bt_login3;
    private javax.swing.JTextField et_date;
    private javax.swing.JTextField et_notes;
    private javax.swing.JTextField et_number;
    private javax.swing.JTextField et_paid;
    private javax.swing.JTextField et_phone_number;
    private javax.swing.JTextField et_price;
    private javax.swing.JTextField et_type;
    private javax.swing.JTextField et_username;
    private javax.swing.JLabel imageHeader;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox_type_of_paying;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tv_notes;
    private javax.swing.JLabel tv_number;
    private javax.swing.JLabel tv_paid;
    private javax.swing.JLabel tv_phone_number;
    private javax.swing.JLabel tv_phone_number1;
    private javax.swing.JLabel tv_price;
    private javax.swing.JLabel tv_type;
    private javax.swing.JLabel tv_type_of_paying;
    private javax.swing.JLabel tv_username;
    // End of variables declaration//GEN-END:variables
}
