/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ameer;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Alaa
 */
public class ShowCustomerDetails extends javax.swing.JFrame {

    /**
     * Creates new form ShowCustomerDetails
     */
    public static ShowCustomerDetails scd;
    public static String customerID;
    public static Bought bought = new Bought();

    public ShowCustomerDetails() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        setIcons();
        setDate(fetchCustomer());
    }

    private void setIcons() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appLogo.png")));
        imageHeader.setIcon(new ImageIcon(getClass().getResource("show.png")));
    }

    private void setDate(Bought bought) {
        et_username.setText(bought.name);
        et_type.setText(bought.type);
        et_date.setText(bought.date);
        et_notes.setText(bought.notes);
        et_number.setText(bought.number);
        et_phone_number.setText(bought.phoneNumber);
        et_restOfMoney.setText(bought.restOfMoney);
        et_price.setText(bought.price);
    }

    private Bought fetchCustomer() {
        Bought bought = new Bought();
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Alaa\\Documents\\NetBeansProjects\\"
                    + "AmeerAbouShaban\\Ameer.mdb", "", "");

            con.setAutoCommit(false);
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            s.execute("select * from Boughts where ID = " + customerID); // select the data from the table
            ResultSet rs = s.getResultSet(); // get any ResultSet that came from our query
            rs.first();

            for (int i = 0; i < rs.getRow(); i++) {
                String id = rs.getString("ID");
                String name = rs.getString("Name");
                String type = rs.getString("Type");
                String phone = rs.getString("Phone");
                String number = rs.getString("Number");
                String price = rs.getString("Price");
                String restOfMoney = rs.getString("RestOfMoney");
                String payingWay = rs.getString("PayingWay");
                String notes = rs.getString("Notes");
                String date = rs.getString("BoughtDate");
                bought.setId(id);
                bought.setName(name);
                bought.setNotes(notes);
                bought.setNumber(number);
                bought.setType(type);
                bought.setPhoneNumber(phone);
                bought.setPrice(price);
                bought.setRestOfMoney(restOfMoney);
                bought.setPayingWay(payingWay);
                bought.setDate(date);
                int priceInt = Integer.parseInt(bought.getPrice());
                int numberInt = Integer.parseInt(bought.getNumber());
                int restOfMoneyInt = Integer.parseInt(bought.getRestOfMoney());
                int totalPrice = priceInt * numberInt;
                int paid = totalPrice - restOfMoneyInt;
                bought.setTotalPrice("" + totalPrice);
                bought.setPaid("" + paid);
                System.out.println(bought.toString());
                rs.next();
            }
            con.close();
            s.close();
            rs.close();
        } catch (Exception ex) {
            System.out.println("Error" + ex.getMessage());
        }
        return bought;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageHeader = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        et_username = new javax.swing.JTextField();
        tv_username = new javax.swing.JLabel();
        et_type = new javax.swing.JTextField();
        tv_type = new javax.swing.JLabel();
        et_phone_number = new javax.swing.JTextField();
        tv_phone_number = new javax.swing.JLabel();
        et_date = new javax.swing.JTextField();
        tv_phone_number1 = new javax.swing.JLabel();
        tv_notes = new javax.swing.JLabel();
        et_notes = new javax.swing.JTextField();
        tv_paid = new javax.swing.JLabel();
        et_restOfMoney = new javax.swing.JTextField();
        et_price = new javax.swing.JTextField();
        et_number = new javax.swing.JTextField();
        tv_number = new javax.swing.JLabel();
        tv_price = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        bt_pay = new javax.swing.JButton();
        bt_showTransactions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ameer/show.png"))); // NOI18N

        et_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_username.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        et_username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_username.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_username.setForeground(new java.awt.Color(2, 177, 225));
        tv_username.setText("الاسم");

        et_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_type.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        et_type.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_type.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_type.setForeground(new java.awt.Color(2, 177, 225));
        tv_type.setText("النوع");

        et_phone_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_phone_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_phone_number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_phone_number.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_phone_number.setForeground(new java.awt.Color(2, 177, 225));
        tv_phone_number.setText("الجوال");

        et_date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_date.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_phone_number1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_phone_number1.setForeground(new java.awt.Color(2, 177, 225));
        tv_phone_number1.setText("التاريخ");

        tv_notes.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_notes.setForeground(new java.awt.Color(2, 177, 225));
        tv_notes.setText("ملاحظات");

        et_notes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_notes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_notes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_paid.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_paid.setForeground(new java.awt.Color(2, 177, 225));
        tv_paid.setText("المتبقي");

        et_restOfMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_restOfMoney.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_restOfMoney.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        et_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_price.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        et_number.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        et_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        et_number.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 175, 255), 1, true));

        tv_number.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_number.setForeground(new java.awt.Color(2, 177, 225));
        tv_number.setText("العدد");

        tv_price.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tv_price.setForeground(new java.awt.Color(2, 177, 225));
        tv_price.setText("السعر");

        bt_back.setBackground(new java.awt.Color(2, 175, 255));
        bt_back.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bt_back.setForeground(new java.awt.Color(255, 255, 255));
        bt_back.setText("رجوع");
        bt_back.setBorder(null);
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        bt_pay.setBackground(new java.awt.Color(2, 175, 255));
        bt_pay.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bt_pay.setForeground(new java.awt.Color(255, 255, 255));
        bt_pay.setText("دفعة");
        bt_pay.setBorder(null);
        bt_pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_payActionPerformed(evt);
            }
        });

        bt_showTransactions.setBackground(new java.awt.Color(2, 175, 255));
        bt_showTransactions.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        bt_showTransactions.setForeground(new java.awt.Color(255, 255, 255));
        bt_showTransactions.setText("عرض الحركات");
        bt_showTransactions.setBorder(null);
        bt_showTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_showTransactionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(imageHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(et_restOfMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(et_price, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(et_number, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tv_number, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tv_price, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tv_paid, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(et_username, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tv_username, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(et_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tv_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(et_type, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tv_type, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(et_date, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tv_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tv_phone_number1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(et_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(bt_showTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(et_price, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tv_price))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tv_number)
                                    .addComponent(et_number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et_restOfMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tv_paid)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tv_username)
                            .addComponent(et_username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(et_type, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tv_type))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tv_phone_number)
                            .addComponent(et_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tv_phone_number1)
                    .addComponent(et_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tv_notes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(et_notes, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_showTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        this.setVisible(false);
        SearchFrame frame = new SearchFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_bt_backActionPerformed

    private void bt_payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_payActionPerformed
        String input = JOptionPane.showInputDialog(null, "الرجاء إدخال الدفعة");
        try {
            int paid = Integer.parseInt(input);
            int restOfMoney = Integer.parseInt(et_restOfMoney.getText());
            int result = restOfMoney - paid;
            System.out.println("Paid " + paid);
            System.out.println("restOfMoney " + restOfMoney);
            System.out.println("result " + result);
            updateBought(result, paid);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "الرجاء إدخال قيم صحيحة");
            return;
        }
    }//GEN-LAST:event_bt_payActionPerformed

    private void bt_showTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_showTransactionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_showTransactionsActionPerformed


    private void updateBought(int result, int paid) {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Alaa\\Documents\\NetBeansProjects\\"
                    + "AmeerAbouShaban\\Ameer.mdb", "", "");
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String query = "update Boughts set Name = ?,Type = ?,Phone = ?,Number = ?,Price = ?,RestOfMoney = ?,PayingWay = ?,Notes = ?,BoughtDate = ? where ID=" + customerID;
            PreparedStatement preparedStmt = con.prepareStatement(query);
            preparedStmt.setString(1, bought.getName());
            preparedStmt.setString(2, bought.getType());
            preparedStmt.setString(3, bought.getPhoneNumber());
            preparedStmt.setString(4, bought.getNumber());
            preparedStmt.setString(5, bought.getPrice());
            preparedStmt.setString(6, "" + result);
            preparedStmt.setString(7, bought.getPayingWay());
            preparedStmt.setString(8, bought.getNotes());
            preparedStmt.setString(9, bought.getDate());
            preparedStmt.executeUpdate();
            con.close();
            s.close();
            insertTransaction(paid);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    private void insertTransaction(int paid) {
        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            Connection con = DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\Alaa\\Documents\\NetBeansProjects\\"
                    + "AmeerAbouShaban\\Ameer.mdb", "", "");

            con.setAutoCommit(false);
            Statement s = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            s.execute("select * from Transactions");
            ResultSet rs = s.getResultSet();
            rs.moveToInsertRow();
            rs.updateString("CustomerID", customerID);
            java.util.Date date = new java.util.Date();
            String dateString = date.getDay() + "/" + date.getMonth() + "/" + date.getYear();
            System.out.println(dateString);
            rs.updateString("TransactionsDate", dateString);
            rs.updateString("Paid", "" + paid);
            rs.insertRow();
            con.commit();
            con.close();
            s.close();
            rs.close();
            JOptionPane.showMessageDialog(null, "تمت الإضافة بنجاح");
        } catch (Exception ex) {
            System.out.println("" + ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCustomerDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_pay;
    private javax.swing.JButton bt_showTransactions;
    private javax.swing.JTextField et_date;
    private javax.swing.JTextField et_notes;
    private javax.swing.JTextField et_number;
    private javax.swing.JTextField et_phone_number;
    private javax.swing.JTextField et_price;
    private javax.swing.JTextField et_restOfMoney;
    private javax.swing.JTextField et_type;
    private javax.swing.JTextField et_username;
    private javax.swing.JLabel imageHeader;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tv_notes;
    private javax.swing.JLabel tv_number;
    private javax.swing.JLabel tv_paid;
    private javax.swing.JLabel tv_phone_number;
    private javax.swing.JLabel tv_phone_number1;
    private javax.swing.JLabel tv_price;
    private javax.swing.JLabel tv_type;
    private javax.swing.JLabel tv_username;
    // End of variables declaration//GEN-END:variables
}
